"""
Standalone CP-SAT solver for Job Shop Scheduling, Flow Shop Scheduling, and Open Shop Scheduling.

This module provides a standalone implementation of CP-SAT solver for JSP/FSP/OSP
that does not depend on the Job_Shop_Scheduling_Benchmark_Environments_and_Instances library.

It reads instances in the optimized JSON format generated by _taillard_to_optimized_json
and solves them using OR-Tools CP-SAT. Supports:
- Job Shop Scheduling (JSP): Each job has its own machine sequence
- Flow Shop Scheduling (FSP): All jobs follow the same machine sequence [0, 1, 2, ..., m-1]
- Open Shop Scheduling (OSP): Operations within a job have no precedence constraints
"""

import collections
from typing import List, Tuple, Optional, Dict, Any

from ortools.sat.python import cp_model


def parse_instance_json(instance_dict: Dict[str, Any]) -> Tuple[List[List[Tuple[int, int]]], int]:
    """
    Parse JSON instance in optimized format.
    
    Parameters
    ----------
    instance_dict : Dict[str, Any]
        Instance dictionary with format:
        {
            "nr_machines": int,
            "nr_jobs": int,
            "jobs": [[[machine_id, processing_time], ...], ...]
        }
    
    Returns
    -------
    Tuple[List[List[Tuple[int, int]]], int]
        A tuple containing:
        - jobs_data: List of jobs, where each job is a list of (machine_id, processing_time) tuples
        - num_machines: Number of machines
    
    Raises
    ------
    ValueError
        If the instance format is invalid
    """
    # Extract basic info
    if "nr_machines" not in instance_dict:
        raise ValueError("Instance missing 'nr_machines' field")
    if "nr_jobs" not in instance_dict:
        raise ValueError("Instance missing 'nr_jobs' field")
    if "jobs" not in instance_dict:
        raise ValueError("Instance missing 'jobs' field")
    
    num_machines = instance_dict["nr_machines"]
    num_jobs = instance_dict["nr_jobs"]
    jobs_raw = instance_dict["jobs"]
    
    # Validate dimensions
    if not isinstance(jobs_raw, list):
        raise ValueError(f"'jobs' must be a list, got {type(jobs_raw)}")
    if len(jobs_raw) != num_jobs:
        raise ValueError(f"Number of jobs in 'jobs' ({len(jobs_raw)}) doesn't match 'nr_jobs' ({num_jobs})")
    
    # Convert jobs to list of tuples
    jobs_data = []
    for job_id, job_operations in enumerate(jobs_raw):
        if not isinstance(job_operations, list):
            raise ValueError(f"Job {job_id} must be a list, got {type(job_operations)}")
        
        job_tasks = []
        for op_idx, operation in enumerate(job_operations):
            if not isinstance(operation, list) or len(operation) != 2:
                raise ValueError(f"Job {job_id}, operation {op_idx} must be [machine_id, processing_time], got {operation}")
            
            machine_id, processing_time = operation[0], operation[1]
            
            # Validate types
            if not isinstance(machine_id, int):
                raise ValueError(f"Job {job_id}, operation {op_idx}: machine_id must be int, got {type(machine_id)}")
            if not isinstance(processing_time, int):
                raise ValueError(f"Job {job_id}, operation {op_idx}: processing_time must be int, got {type(processing_time)}")
            
            # Validate machine_id is in valid range
            if machine_id < 0 or machine_id >= num_machines:
                raise ValueError(f"Job {job_id}, operation {op_idx}: machine_id {machine_id} out of range [0, {num_machines})")
            
            # Validate processing_time is positive
            if processing_time <= 0:
                raise ValueError(f"Job {job_id}, operation {op_idx}: processing_time must be positive, got {processing_time}")
            
            job_tasks.append((machine_id, processing_time))
        
        jobs_data.append(job_tasks)
    
    # Validate that all jobs have at least one operation
    for job_id, job in enumerate(jobs_data):
        if len(job) == 0:
            raise ValueError(f"Job {job_id} has no operations")
    
    return jobs_data, num_machines


def build_scheduling_model(jobs_data: List[List[Tuple[int, int]]], num_machines: int) -> Tuple[cp_model.CpModel, Dict]:
    """
    Build CP-SAT model for Job Shop Scheduling or Flow Shop Scheduling.
    
    This function works for both JSP and FSP. The difference is in the instance data:
    - JSP: Each job can have different machine sequences
    - FSP: All jobs follow the same machine sequence [0, 1, 2, ..., m-1]
    
    Parameters
    ----------
    jobs_data : List[List[Tuple[int, int]]]
        List of jobs, where each job is a list of (machine_id, processing_time) tuples
    num_machines : int
        Number of machines
    
    Returns
    -------
    Tuple[cp_model.CpModel, Dict]
        A tuple containing:
        - model: The CP-SAT model
        - vars: Dictionary containing model variables (key: 'all_tasks')
    """
    all_machines = range(num_machines)
    
    # Compute horizon dynamically as the sum of all durations
    horizon = sum(processing_time for job in jobs_data for _, processing_time in job)
    
    # Create the model
    model = cp_model.CpModel()
    
    # Named tuple to store information about created variables
    task_type = collections.namedtuple("task_type", "start end interval")
    
    # Create job intervals and add to the corresponding machine lists
    all_tasks = {}
    machine_to_intervals = collections.defaultdict(list)
    
    for job_id, job in enumerate(jobs_data):
        for task_id, (machine_id, duration) in enumerate(job):
            suffix = f"_{job_id}_{task_id}"
            start_var = model.NewIntVar(0, horizon, "start" + suffix)
            end_var = model.NewIntVar(0, horizon, "end" + suffix)
            interval_var = model.NewIntervalVar(
                start_var, duration, end_var, "interval" + suffix
            )
            all_tasks[job_id, task_id] = task_type(
                start=start_var, end=end_var, interval=interval_var
            )
            machine_to_intervals[machine_id].append(interval_var)
    
    # Create and add disjunctive constraints (no overlap on each machine)
    for machine in all_machines:
        model.AddNoOverlap(machine_to_intervals[machine])
    
    # Precedences inside a job (operations must execute in order)
    for job_id, job in enumerate(jobs_data):
        for task_id in range(len(job) - 1):
            model.Add(all_tasks[job_id, task_id + 1].start >= all_tasks[job_id, task_id].end)
    
    # Makespan objective (minimize maximum completion time)
    makespan = model.NewIntVar(0, horizon, "makespan")
    model.AddMaxEquality(
        makespan,
        [all_tasks[job_id, len(job) - 1].end for job_id, job in enumerate(jobs_data)]
    )
    model.Minimize(makespan)
    
    return model, {"all_tasks": all_tasks}


def build_openshop_model(jobs_data: List[List[Tuple[int, int]]], num_machines: int) -> Tuple[cp_model.CpModel, Dict]:
    """
    Build CP-SAT model for Open Shop Scheduling.
    
    Open Shop differs from JSP/FSP in that:
    - Operations within a job have NO precedence constraints
    - Operations of the same job cannot overlap (no-overlap constraint per job)
    - Operations on the same machine cannot overlap (no-overlap constraint per machine)
    
    Parameters
    ----------
    jobs_data : List[List[Tuple[int, int]]]
        List of jobs, where each job is a list of (machine_id, processing_time) tuples
    num_machines : int
        Number of machines
    
    Returns
    -------
    Tuple[cp_model.CpModel, Dict]
        A tuple containing:
        - model: The CP-SAT model
        - vars: Dictionary containing model variables (key: 'all_tasks')
    """
    all_machines = range(num_machines)
    
    # Compute horizon dynamically as the sum of all durations
    horizon = sum(processing_time for job in jobs_data for _, processing_time in job)
    
    # Create the model
    model = cp_model.CpModel()
    
    # Named tuple to store information about created variables
    task_type = collections.namedtuple("task_type", "start end interval")
    
    # Create job intervals and add to the corresponding machine lists and job lists
    all_tasks = {}
    machine_to_intervals = collections.defaultdict(list)
    job_to_intervals = collections.defaultdict(list)
    
    for job_id, job in enumerate(jobs_data):
        for task_id, (machine_id, duration) in enumerate(job):
            suffix = f"_{job_id}_{task_id}"
            start_var = model.NewIntVar(0, horizon, "start" + suffix)
            end_var = model.NewIntVar(0, horizon, "end" + suffix)
            interval_var = model.NewIntervalVar(
                start_var, duration, end_var, "interval" + suffix
            )
            all_tasks[job_id, task_id] = task_type(
                start=start_var, end=end_var, interval=interval_var
            )
            machine_to_intervals[machine_id].append(interval_var)
            job_to_intervals[job_id].append(interval_var)
    
    # Create and add disjunctive constraints (no overlap on each machine)
    for machine in all_machines:
        model.AddNoOverlap(machine_to_intervals[machine])
    
    # No overlap constraints for jobs (operations of same job cannot overlap)
    # This is the key difference from JSP/FSP - no precedence, just no-overlap
    for job_id in job_to_intervals:
        model.AddNoOverlap(job_to_intervals[job_id])
    
    # Makespan objective (minimize maximum completion time)
    # For Open Shop, we need to find the maximum end time across all operations
    makespan = model.NewIntVar(0, horizon, "makespan")
    all_end_times = []
    for job_id, job in enumerate(jobs_data):
        for task_id in range(len(job)):
            all_end_times.append(all_tasks[job_id, task_id].end)
    model.AddMaxEquality(makespan, all_end_times)
    model.Minimize(makespan)
    
    return model, {"all_tasks": all_tasks}


def solve_standalone_cpsat(
    instance_data: Dict[str, Any],
    time_limit: float = 60.0,
    problem_type: str = "jsp"
) -> Tuple[float, Optional[Dict[str, Any]]]:
    """
    Solve Job Shop Scheduling, Flow Shop Scheduling, or Open Shop Scheduling problem using standalone CP-SAT solver.
    
    This solver works for JSP, FSP, and OSP instances. The instance format is the same:
    - JSP: Each job has its own machine sequence (can be different per job)
    - FSP: All jobs follow the same machine sequence [0, 1, 2, ..., m-1]
    - OSP: Operations within a job have no precedence constraints
    
    Parameters
    ----------
    instance_data : Dict[str, Any]
        Instance dictionary with format:
        {
            "nr_machines": int,
            "nr_jobs": int,
            "jobs": [[[machine_id, processing_time], ...], ...]
        }
    time_limit : float, optional
        Solver time limit in seconds. Default is 60.0.
    problem_type : str, optional
        Problem type: "jsp" for Job Shop, "fsp" for Flow Shop, or "osp" for Open Shop. Default is "jsp".
    
    Returns
    -------
    Tuple[float, Optional[Dict[str, Any]]]
        A tuple containing:
        - makespan: float - the optimal/feasible makespan value (or NaN if no solution found)
        - schedule: Optional[Dict] - detailed schedule information from results
          Format: List of job info dicts, each with "job", "tasks" (list of task dicts
          with "task", "start", "machine", "duration")
    """
    try:
        # Parse instance
        jobs_data, num_machines = parse_instance_json(instance_data)
        
        # Build CP-SAT model based on problem type
        if problem_type == "osp":
            model, vars = build_openshop_model(jobs_data, num_machines)
        else:
            # JSP and FSP use the same model (difference is only in instance data)
            model, vars = build_scheduling_model(jobs_data, num_machines)
        all_tasks = vars['all_tasks']
        
        # Create solver and set time limit
        solver = cp_model.CpSolver()
        solver.parameters.max_time_in_seconds = time_limit
        
        # Solve
        status = solver.Solve(model)
        
        # Check if solution found
        if status in [cp_model.OPTIMAL, cp_model.FEASIBLE]:
            makespan = float(solver.ObjectiveValue())
            
            # Extract schedule
            schedule = [
                {
                    "job": job_id,
                    "tasks": [
                        {
                            "task": task_id,
                            "start": solver.Value(all_tasks[job_id, task_id].start),
                            "machine": machine_id,
                            "duration": processing_time,
                        }
                        for task_id, (machine_id, processing_time) in enumerate(job)
                    ]
                }
                for job_id, job in enumerate(jobs_data)
            ]
            
            return makespan, schedule
        else:
            # No solution found
            return float("nan"), None
            
    except Exception as e:
        print(f"[Error] Standalone CP-SAT solver failed: {e}")
        import traceback
        traceback.print_exc()
        return float("nan"), None

